is_dnn: false

data:
  eval_dt: 1
  root: "../data/hdf5"
  dataset: "MVSEC"
  sequence: "15_05"
  height: 480
  width: 640
  load_gt_flow: True
  gt: "../data/gt_flow"
  n_events_per_batch: 30000
  ind1: 0
  ind2: 30000

output:
  output_dir: "../outputs/secrets/15_05"
  show_interactive_result: false

solver:
  method: "pyramidal_patch_contrast_maximization"
  time_aware: False
  patch:
    initialize: "random"
    scale: 5
    crop_height: 480
    crop_width: 640
    filter_type: "bilinear"
  motion_model: "2d-translation"
  warp_direction: "first"
  parameters:
    - "trans_x"
    - "trans_y"
  cost: "hybrid"
  outer_padding: 0
  cost_with_weight:
    multi_focal_normalized_gradient_magnitude: 1.
    total_variation: 0.01
  iwe:
    method: "bilinear_vote"
    blur_sigma: 1

optimizer:
  n_iter: 40
  method: "Newton-CG"
  max_iter: 25
  parameters:
    trans_x:
      min: -150
      max: 150
    trans_y:
      min: -150
      max: 150
