data:
    path: ../data/hdf5
    mode: time  # events/time/gtflow
    window: 0.01666667
    passes_loss: 10
    cache: False

loader:
    resolution: [480, 640] # H x W
    augment: []
    max_num_grad_events: Null
    gpu: 0
    seed: Null  # random if Null

metrics:
    warping: Iterative  # Linear/Iterative
    name: ["FWL", "RSAT", "AEE"]

vis:
    enabled: True
    px: 400
    bars: True
    store: True
    mask_output: True
    dynamic: False
#    show: ["flow_bw"]  # Null for everything
    show: Null